version: "3.1"

services:
  app:
    image: bitpackio/testware
    container_name: testware-app-2
    environment:
      - APP_URL="http://localhost"
      - APP_PORT=80
      - APP_DEBUG=true
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=5aff081622cd69
      - MAIL_PASSWORD=cc817196122ee5
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS=null
      - MAIL_FROM_NAME=null
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=testware-2
      - DB_USERNAME=testWareDbUser
      - DB_PASSWORD=9VB15VpFnJFMx
    ports:
      - 80:80
    volumes:
      - ./testware-files:/var/www/html/storage/app
      - //c/xampp/htdocs/medtestware/:/var/www/html
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=testware-2
      - POSTGRES_USER=testWareDbUser
      - POSTGRES_PASSWORD=9VB15VpFnJFMx
    ports:
      - 5432:5432
    container_name: testware-db-2
    working_dir: /data/pgsql
    volumes:
      - ./db-data-2:/var/lib/postgresql/data
