version: "3.1"

services:
  app:
    image: bitpackio/testware
    container_name: testware-app
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./testware-files:/var/www/html/storage/app
    depends_on:
      - db

  #
  #  adminer:
  #    image: adminer
  #    restart: always
  #    ports:
  #      - 8085:8080
  #

  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    container_name: testware-db
    working_dir: /data/pgsql
    volumes:
      - ./db-data:/var/lib/postgresql/data
