version: "3.1"

services:
  app:
    image: bitpackio/testware
    container_name: testware-app
    env_file:
      - app.env
    ports:
      - 80:80
    volumes:
      - ./testware-files:/var/www/html/storage/app
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  db:
    image: postgres:11
    restart: always
    env_file:
      - db.env
    ports:
      - 5432:5432
    container_name: testware-db
    working_dir: /data/pgsql
    volumes:
      - ./testware-db-data:/var/lib/postgresql/data
